services:
  - type: web
    name: wallet-api
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    healthCheckPath: /ping
    envVars:
      - key: DATA_DIR
        value: /tmp
